# =====================================================
# BatataQuente - Configuração principal
# =====================================================

# Configurações gerais
# ----------------------------------------------------
# language: Idioma do plugin (ptbr ou enus)
# prefix-enabled: Se o prefixo deve ser mostrado nas mensagens
language: ptbr
prefix-enabled: true

# Configurações de debug
# ----------------------------------------------------
# debug: Quando ativado, mensagens de debug serão mostradas
debug: false

# Configurações de logging
# ----------------------------------------------------
# enabled: Ativa/desativa o sistema de logs
# debug-to-file: Se mensagens de debug devem ser salvas no arquivo
# max-log-days: Número máximo de dias para manter logs (0 = manter todos)
logging:
  enabled: true
  debug-to-file: true
  max-log-days: 7

# =====================================================
# Fim da configuração
# =====================================================