name: NesquikBatataQuente
version: ${project.version}
description: Plugin de BatataQuente para servidor Minecraft
author: oNyell
website: https://onyell.com
main: com.onyell.batataquente.Main
depend: [kCore]